#!/bin/sh
# -*- sh -*-
# vim: set syntax=sh
# code: language=shellscript

# Copyright (c) 2022 Michael Federczuk
# SPDX-License-Identifier: MPL-2.0 AND Apache-2.0

set -o errexit
set -o nounset

argv0() {
	if [ "$0" = "$(realpath -s -- "$0")" ]; then
		printf '%s' "$(basename -- "$0")"
	else
		printf '%s' "$0"
	fi
}

log() {
	case $# in
		(0)
			echo 'log: missing argument: <message>' >&2
			exit 123
			;;
		(1) ;;
		(*)
			echo "log: too many arguments: $(($# - 1))" >&2
			exit 123
			;;
	esac

	printf -- '%s\n' "$1" >&2
}
errlog() {
	case $# in
		(0)
			echo 'error: missing argument: <message>' >&2
			exit 123
			;;
		(1) ;;
		(*)
			echo "error: too many arguments: $(($# - 1))" >&2
			exit 123
			;;
	esac

	log "$(argv0): $1"
}

root_dir_path="$(realpath --relative-to=. -- "$0")"
root_dir_path="$(dirname -- "$root_dir_path")"
readonly root_dir_path

templates_location_dir_path="$(realpath --relative-base=. -ms -- "$root_dir_path/templates")"
readonly templates_location_dir_path

if [ ! -e "$templates_location_dir_path" ]; then
	errlog "$templates_location_dir_path: no such directory"
	exit 24
fi
if [ ! -d "$templates_location_dir_path" ]; then
	errlog "$templates_location_dir_path: not a directory"
	exit 26
fi

# region args

print_usage() {
	log "usage: $(argv0) (--list | <source> <target>)"
}

if [ "${1-}" = '--help' ]; then
	print_usage
	exit
fi

list_templates=false

case $# in
	(0)
		errlog 'missing arguments: (--list | <source> <target>)'
		print_usage
		exit 3
		;;
	(1)
		case "$1" in
			('--list')
				list_templates=true
				;;
			(*)
				errlog 'missing argument: <target>'
				print_usage
				exit 3
				;;
		esac
		;;
	(2)
		case "$1" in
			('--list')
				errlog "too many arguments: $(($# - 1))"
				print_usage
				exit 4
				;;
			(*)
				# nothing since correct usage
				;;
		esac
		;;
	(*)
		case "$1" in
			('--list') expected_argc=1 ;;
			(*)        expected_argc=2 ;;
		esac

		errlog "too many arguments: $(($# - expected_argc))"
		print_usage
		exit 4
		;;
esac

if $list_templates; then
	printf '%s\n' "$templates_location_dir_path/"*'.tex' | sed -E s%'(.*/)?([^/]+)\.tex$'%'\2'%
	exit
fi

source="$1"
if [ -z "$source" ]; then
	errlog 'argument 1: must not be empty'
	exit 9
fi
source="$(realpath -ms --relative-base=. -- "$source")"

target="$2"
if [ -z "$target" ]; then
	errlog 'argument 2: must not be empty'
	exit 9
fi
target="$(realpath -ms --relative-base=. -- "$target")"

if [ ! -e "$source" ]; then
	fallback=''

	if ! printf '%s' "$source" | grep -Eq '/'; then
		tmp="$templates_location_dir_path/$source.tex"

		if [ -f "$tmp" ]; then
			fallback="$tmp"
		fi

		unset -v tmp
	fi

	if [ -z "$fallback" ]; then
		errlog "$1: no such file"
		exit 24
	fi

	source="$fallback"
	unset -v fallback
fi
if [ ! -f "$source" ]; then
	errlog "$1: not a regular file"
	exit 26
fi

if [ -e "$target" ] && [ ! -f "$target" ]; then
	errlog "$2: not a regular file"
	exit 26
fi

readonly source target

# endregion

today="$(date +%s)"
readonly today

day="$(date -d"@$today" +%d)"
month="$(date -d"@$today" +%m)"
year="$(date -d"@$today" +%Y)"
readonly day month year

sed -E /'^[[:space:]]*%%'/d\;s/'[[:space:]]*%%.*$'//\;s/'<DAY>'/"$day"/g\;s/'<MONTH>'/"$month"/g\;s/'<YEAR>'/"$year"/g "$source" > "$target"
